---
- name: Create VM with defaults
  hosts: localhost
  become: true
  tasks:
    - name: Crear una máquina virtual
      azure_rm_virtualmachine:
        name: my-vm
        location: eastus2
        resource_group: devops_lab
        vm_size: Standard_D2s_v3
        admin_username: admin
        admin_password: Contraseña_muy_segura$
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
