---
- name: Crear archivo en /tmp
  hosts: 10.128.0.24
  become: true
  tasks:
    - name: Crear archivo "archivo_creado.txt"
      ansible.builtin.file:
        path: /tmp/archivo_creado.txt
        state: touch
        mode: '0644'
        content: "Este archivo fue creado por un playbook de Ansible."
