---
- name: Create VM with defaults
  hosts: localhost
  become: true
  vars:
    resource_group: "devops_lab"  # Reemplace con su nombre de grupo de recursos
    vm_name: "my-vm"  # Reemplace con el nombre de su máquina virtual
    admin_username: "admin"
    admin_password: "Contraseña_muy_segura$" 
  tasks:
    - name: Crear una máquina virtual
      azure_rm_virtualmachine:
        name: "my-vm"
        location: eastus2
        resource_group: "devops_lab"
        vm_size: "Standard_D2s_v3"
        admin_username: "admin"
        admin_password: "Contraseña_muy_segura$"
        custom_data: "#!/bin/bash\necho '¡VM creada exitosamente!' > /etc/motd"  # New parameter
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
