---
- name: Crear archivo en /tmp
  hosts: rhel8
  become: true
  tasks:
    - name: Crear archivo "archivo_creado.txt"
      file:
        path: /tmp/archivo_creado.txt
        state: touch
        mode: '0644'
        content: "Este archivo fue creado por un playbook de Ansible."
