---
- name: Create VM with defaults
  hosts: localhost
  become: true
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: demo
        location: eastus
        tags:
          testing: testing
