---
- name: remove logs
  hosts: node3
  tasks:
  - name: Delete files older than 30 days
    find:
      paths: /var/log/
      age: 30d
      age_stamp: mtime
    register: old_files
  
  - name: Remove older files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ old_files.files }}"
