---
- name: Download the file from storageblob
  hosts: ansible-1
  tasks:
    - name: Download the file
      azure_rm_storageblob:
        resource_group: devops_lab
        storage_account_name: devopsstorage17
        container: images-redhat
        blob: descarga.png
        dest: /tmp/descarga.png
